#!/bin/bash
# -*- mode: sh -*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id$
#
#***********************************************************EndPNNLCopyright*

# set -x

scriptPath0="${BASH_SOURCE[0]}" # works when script is sourced (unlike $0)
scriptPath=$(readlink -f "${scriptPath0}")
scriptCmd=${scriptPath##*/} # cf. $(basename ...)
scriptDir=${scriptPath%/*}  # cf. $(dirname ...)

#****************************************************************************

opt_ubench='iozone'
opt_out_fnm=''

ior_path="${HOME}/app/ior/ior.git/MYINSTALL/bin/ior"
iozone_path="${HOME}/app/iozone/iozone/src/current/iozone"

max_ranks=64

max_hours=24

#****************************************************************************
# Parse arguments
#****************************************************************************

die()
{
    cat <<EOF 1>&2
${scriptCmd}: $*
Use '${scriptCmd} -h' for usage.
EOF
    exit 1
}

usage()
{
    cat <<EOF
Usage: ${scriptCmd} [--ubench ior|iozone] ...
EOF
    exit 0
}

#-----------------------------------------------------------
# optional arguments
#-----------------------------------------------------------
while [[ $# -gt 0 ]] ; do

    arg="$1"
    shift # past argument
    
    case "${arg}" in
	-h | --help )
	    usage
	    ;;

	--ubench )
	    opt_ubench="$1"
	    shift # past value
	    ;;

	-o | --output )
	    opt_out_fnm="$1"
	    shift # past value
	    ;;
      	
	* ) # unknown option
	    die "unknown option '$1'"
	    ;;
    esac
done

#-----------------------------------------------------------
# required args
#-----------------------------------------------------------

#if [[ -z ${xxx} ]] ; then
#    die "no CFGProf path"
#fi


#****************************************************************************
# 
#****************************************************************************

# cf. ~/1modsim-tools-svn/palm/trunk/palm-task/palm-task-genfp

my_hostname=${HOSTNAME}

fs_path=$(readlink -f .)

out_fnm="${scriptCmd}-$(date --iso-8601=minutes).log"
[[ -n ${opt_out_fnm} ]] && out_fnm="${opt_out_fnm}"

#****************************************************************************
# 
#****************************************************************************

# sets "mpi_launcher"
mk_mpi_launcher()
{
    local tasks=$1
    mpi_launcher="mpiexec -n ${tasks}"
    case "${my_hostname}" in
	bluesky* )
	    # --ntasks-per-node=24
	    ((nodes= ${tasks} / 24 + 1))
	    mpi_launcher="srun -N ${nodes} -n ${tasks} -t 00:10:00"
	    ;;
	seapearl* )
	    ((nodes= ${tasks} / 20 + 1))
	    mpi_launcher="srun -p ivy -N ${nodes} -t 00:10:00 mpiexec -n ${tasks}"
	    ;;
	* ) # unknown option
	    die "unknown launcher for '${my_hostname}'"
	    ;;
    esac
}


kb2_to_mb10_per_ps()
{
    local n_ps=$1
    local bw=$2
    echo "(${bw} * 1024) / (10^6 * ${n_ps})" | bc -l
}


#****************************************************************************
# 
#****************************************************************************

re_tasks="tasks[:blank:]*: ([[:digit:]]+)"
re_bw="^Max (Read|Write): *([0-9.]+) MiB/sec \(([0-9.]+) MB/sec"

parse_ior()
{
    local n_match=0
    while IFS= read line; do
	#echo ${line}
	#if ((n_match >= 2)) ; then
	#    continue
	if [[ ${line} =~ ${re_tasks} ]] ; then
	    local ranks=${BASH_REMATCH[1]}
	    ((n_match++))
	elif [[ ${line} =~ ${re_bw} ]] ; then
	    local type=${BASH_REMATCH[1]}
	    local bw2=${BASH_REMATCH[2]}  # MiB/s
	    local bw10=${BASH_REMATCH[3]} # MB/s
	    ((n_match++))
	fi
    done
    printf "  %5s %3d: %8.1f MB/s; %8.1f MiB/s\n" ${type} ${ranks} ${bw10} ${bw2}
}


re_ioz_x="Children see throughput for"
re_ioz_y="[[:blank:]]+= +([0-9.]+) kB/sec"
re_re_wr="${re_ioz_x} +([0-9]+) rewriters${re_ioz_y}"
re_re_rd="${re_ioz_x} +([0-9]+) re-readers${re_ioz_y}"
re_rnd_rd="${re_ioz_x} +([0-9]+) random readers${re_ioz_y}"
re_rnd_wr="${re_ioz_x} +([0-9]+) random writers${re_ioz_y}"

parse_iozone()
{
    local type=$1
    local n_match=0
    while IFS= read line; do
	#echo ${line}
	#if ((n_match >= 3)) ; then
	#    continue
	if [[ ${line} =~ ${re_re_wr} ]] ; then
	    local ranks=${BASH_REMATCH[1]}
	    local re_wr_bw2=${BASH_REMATCH[2]} # KiB/s all ps
	    local re_wr_bw10=$(kb2_to_mb10_per_ps ${ranks} ${re_wr_bw2}) # MB/s
	    ((n_match++))
	elif [[ ${line} =~ ${re_re_rd} ]] ; then
	    local ranks=${BASH_REMATCH[1]}
	    local re_rd_bw2=${BASH_REMATCH[2]} # KiB/s all ps
	    local re_rd_bw10=$(kb2_to_mb10_per_ps ${ranks} ${re_rd_bw2}) # MB/s
	    ((n_match++))
	elif [[ ${line} =~ ${re_rnd_rd} ]] ; then
	    local ranks=${BASH_REMATCH[1]}
	    local rnd_rd_bw2=${BASH_REMATCH[2]} # KiB/s all ps
	    local rnd_rd_bw10=$(kb2_to_mb10_per_ps ${ranks} ${rnd_rd_bw2}) # MB/s
	    ((n_match++))
	elif [[ ${line} =~ ${re_rnd_wr} ]] ; then
	    local ranks=${BASH_REMATCH[1]}
	    local rnd_wr_bw2=${BASH_REMATCH[2]} # KiB/s all ps
	    local rnd_wr_bw10=$(kb2_to_mb10_per_ps ${ranks} ${rnd_wr_bw2}) # MB/s
	    ((n_match++))
	fi
    done
    
    printf "   %5s %3d  re-wr, re-rd: %8.1f MB/s/ps; %8.1f MB/s/ps\n" ${type} ${ranks} ${re_wr_bw10} ${re_rd_bw10}
    printf "   %5s %3d rnd-wr,rnd-rd: %8.1f MB/s/ps; %8.1f MB/s/ps\n" ${type} ${ranks} ${rnd_wr_bw10} ${rnd_rd_bw10}
}


#****************************************************************************

ior_w_opts="-F -a=POSIX -w -s=1 -b=256m -t=16m -i=1 -vv" # -e
ior_r_opts="-F -a=POSIX -r -s=1 -b=256m -t=16k -i=1 -vv"

iozone_w_opts="-i 0      -i 2 -s 256m -r 16m -t"
iozone_r_opts="-i 0 -i 1 -i 2 -s 256m -r 16k -t"

dat_fnm_stem="io.dat"
dat_fnm_path="${fs_path%/}/${dat_fnm_stem}" # strip trailing /


do_ior()
{
    local date_str=$(date --iso-8601=minutes)

    printf -- "- ${date_str}\n" >> "${out_fnm}"

    #----------------------------------------
    # Write tests
    #----------------------------------------

    printf -- "- ${date_str}: write"
    for (( n_rank = 1; n_rank <= max_ranks; n_rank *= 2 )) ; do
    	printf " ${n_rank}"
    	mk_mpi_launcher ${n_rank}
    	local cmd="${mpi_launcher} ${ior_path} ${ior_w_opts} -o ${dat_fnm_path}"
    	#printf "\n${cmd}\n"
    	${cmd}  | parse_ior >> "${out_fnm}"
    	sleep 10
    done

    #----------------------------------------
    # Read tests (first create pristine data)
    #----------------------------------------

    # N.B.: without fsyncs, ior may exit without writing all data
    mk_mpi_launcher ${max_ranks}
    ${mpi_launcher} ${ior_path} ${ior_w_opts} -Y -k -o ${dat_fnm_path} > /dev/null

    printf "; read"
    for (( n_rank = 1; n_rank <= max_ranks; n_rank *= 2 )) ; do
	printf " ${n_rank}"
	mk_mpi_launcher ${n_rank}
	local cmd="${mpi_launcher} ${ior_path} ${ior_r_opts} -k -o ${dat_fnm_path}"
	#printf "\n${cmd}\n"
	${cmd} | parse_ior >> "${out_fnm}"
	sleep 10
    done
    printf "\n"

    \rm -f "${dat_fnm_path}".*
}


do_iozone()
{
    local date_str=$(date --iso-8601=minutes)

    printf -- "- ${date_str}\n" >> "${out_fnm}"

    #----------------------------------------
    # 
    #----------------------------------------

    printf -- "- ${date_str}: "
    for (( n_rank = 1; n_rank <= max_ranks; n_rank *= 2 )) ; do
    	printf " ${n_rank} (wr"
    	local cmd="${iozone_path} ${iozone_w_opts} ${n_rank}"
    	#printf "\n${cmd}\n"
    	${cmd} | parse_iozone "write" >> "${out_fnm}"
    	sleep 10

	printf "/rd)"
	local cmd="${iozone_path} ${iozone_r_opts} ${n_rank}"
    	#printf "\n${cmd}\n"
    	${cmd} | parse_iozone "read" >> "${out_fnm}"
	sleep 10
    done

    printf "\n"
}

#****************************************************************************

((hour_sec = 60 * 60))

do_ior_loop()
{
    printf "* ior: ${ior_path}\n" | tee -a "${out_fnm}"
    printf "* ior write: ${ior_w_opts}\n" | tee -a "${out_fnm}"
    printf "* ior read : ${ior_r_opts}\n" | tee -a "${out_fnm}"
    printf "* hostname: ${my_hostname}\n" | tee -a "${out_fnm}"
    printf "* file system: ${fs_path} (${dat_fnm_path})\n" | tee -a "${out_fnm}"
    
    for (( hour = 1; hour <= max_hours; hour++ )) ; do
	do_ior
	sleep ${hour_sec}
    done
}


do_iozone_loop()
{
    printf "* iozone: ${iozone_path}\n" | tee -a "${out_fnm}"
    printf "* iozone write: ${iozone_w_opts}\n" | tee -a "${out_fnm}"
    printf "* iozone read : ${iozone_r_opts}\n" | tee -a "${out_fnm}"
    printf "* hostname: ${my_hostname}\n" | tee -a "${out_fnm}"
    printf "* file system: ${fs_path}\n" | tee -a "${out_fnm}"
    
    for (( hour = 1; hour <= max_hours; hour++ )) ; do
	do_iozone
	sleep ${hour_sec}
    done
}

# watch --interval=3600 <me>

# at now + 1 hour -m -f ~/scheduledTask.sh
# at 06:00 -m -f ~/scheduledTask.sh

#****************************************************************************


printf "" > "${out_fnm}"

if [[ ${opt_ubench} = iozone ]] ; then
    do_iozone_loop
elif [[ ${opt_ubench} = ior ]] ; then
    do_ior_loop
fi
