# -*-Mode: makefile;-*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id$
#
#***********************************************************EndPNNLCopyright*

#****************************************************************************
# $HeadURL$
#
# Nathan Tallent
#****************************************************************************

CXX = mpicxx

#****************************************************************************

mpiaffinity = mpi-affinity

$(mpiaffinity)_SRCS = main.cpp

$(mpiaffinity)_CXXFLAGS = -O3 -g

$(mpiaffinity)_LDFLAGS =

$(mpiaffinity)_LIBS =

$(mpiaffinity)_LDADD =

#****************************************************************************

MK_SUBDIRS =

MK_PROGRAMS_CXX = $(mpiaffinity)

include ../Makefile-template.mk

#****************************************************************************
